export enum CURRENCIES_ENUM {
    UAH = 'UAH',
    USD = 'USD',
    EUR = 'EUR'
}

export enum ACTIONS_ENUM {
    CHANGE_LEFT_CURRENCY = 'CHANGE_LEFT_CURRENCY',
    CHANGE_RIGTH_CURRENCY = 'CHANGE_RIGTH_CURRENCY',
    CHANGE_LEFT_VALUE = 'CHANGE_LEFT_VALUE',
    CHANGE_RIGHT_VALUE = 'CHANGE_RIGHT_VALUE'
}
